---
title: 在公共库中的好用统一错误处理
author: Dadajia
created: 2024-11-21 17:18
last_modified: 2024-12-11 19:00
---
# 在公共库中的好用统一错误处理
当我们对公共库封装时，为了减少用户的使用负担，最好是内部已经做好了完善的错误处理机制。

假设我们开发了一个工具模块，代码如下:
```js
// utils.js
export default {
    fun(fn) {
        fn && fn()
    }
}
```
该模块导出一个对象，其中fun属性是一个函数，它接受一个函数作为参数，并调用该参数时会执行该回调函数
```js
// 外部
import utils from './utils.js'
utils.foo(()=>{})
```
如果我们没有进行完善的错误处理，那么可能需要用户自己完善这部分
```js
import utils from './utils.js'
utils.foo(()=>{
    try {
        //...
    } catch(e) {/* ... */}
})
```
如果在utils中有一万个函数，岂不是每个都需要用户自己写了？那么使用负担就很重。但是我们可以在utils内部对每个函数进行错误处理，如下：
```js
// utls.js
export default {
    fun1 (fn) {
        try {
            fn && fn()
        } catch(e) {/* 错误处理 */}
    },
    fun2 (fn) {
        try {
            fn && fn()
        } catch(e) {/* 错误处理 */}
    },
    fun3(){} // ...
}
```
显然我们可以将上述的`try catch`模块提取出来作为一个函数 `callWithErrorHanding`
```js
export default {
    fun1(fn) {
        callWithErrorHanding(fn)
    },
    fun2(fn) {
        callWithErrorHanding(fn)
    }
}
function callWithErrorHanding(fn) {
    try {
        fn && fn();
    } catch (e) {/* 错误处理 */}
}
```
可以看到代码变得简洁多了，但真正的好处是能给用户提供统一的错误处理接口，如下：
```js
let handleError = null;
export default {
    fun1(fn) { callWithErrorHanding(fn) },
    fun2(fn) { callWithErrorHanding(fn) },
    // ...
    // 注册统一的错误处理函数
    registerErrorHandler(fn) {
        handerError = fn;
    }
}
function callWithErrorHanding(fn) {
    try {
        fn && fn();
    } catch (e) {
        handleError(e)
    }
}
```
这样我们就成功地将错误处理的具体行为交给用户去注册，同时又避免了用户自己写繁杂冗余的错误判断代码，让用户侧的代码变得简洁且且健壮，如下：
```js
import utils from './utils.js'
// 注册错误处理程序
utils.registerErrorHandler((e)=>{
    /* 具体你要做的错误处理操作 */
})
utils.fun1(()=>{/* 回调 */})
utils.fun2(()=>{/* 回调 */})
```
这样错误处理的能力完全由用户控制，用户既可以选择忽略错误，也可以调用上述程序将错误上报给监控系统。

当然你可能觉得传入一个回调函数的情况有点复杂，通常我们应当是直接输入参数调用的，那么让我们写一个更通用的写法。
```js
// utils.js
let handleError = null;
function callWithErrorHanding(fn,...args) {
    try {
        return fn(...args)
    } catch (e) {
        handleError && handleError(e)
    }
}
export default {
    toUpper(str) { // 工具函数：将传入的字符串字母全部转化为大写
        return callWithErrorHanding((str)=>{ // 这个回调函数写的是真正的函数内容
            if (typeof str !== 'string') {
                throw new Error('出错了！输入的参数必须是字符串')
            }
            return str.toUpperCase()
        }, str)
    },
    registerErrorHandler(fn) {
        handleError = fn;
    }
}
// main.js
import utils from './utils.js'
// 注册错误处理程序
utils.registerErrorHandler((e) => {/* 这里可以添加更多的错误处理逻辑，例如上报错误到监控系统 */});
utils.toUpper('hello'); // 输出HELLO
utils.toUpper(1); // 触发错误
```
好的，现在我们实现了对传入普通参数函数的处理。

但是，实际的函数操作都是匿名的，这在开发时极其不符合习惯，我们一般都是先不考虑那么多先开发好函数的功能，作为开发者我们不应当过度关注callWithErrorHanding包装函数的操作。

所以，我们可以通过工厂函数来简化开发者的工作流程，使得开发者可以专注于编写实际的函数逻辑，而不需要过多关注错误处理机制的实现。
```js
// utils.js
let handleError = null;
// 通用错误处理函数
function callWithErrorHanding(fn,...args) {
    try {
        return fn(...args); // 执行实际函数逻辑
    } catch (e) {
        handleError && handleError(e)
    }
}
// 工厂函数，用于生成带错误处理机制的工具函数
function createSafeFunction(fn) {
    return function(...args) {
        return callWithErrorHanding(fn,...args)
    }
}

// 实际使用，假设我们写了大写转换函数
function toUpper(str) {
    if (typeof str !== 'string') {
        throw new Error('出错了！输入的参数必须是字符串');
    }
    return str.toUpperCase();
}

export default {
    toUpper:  createSafeFunction(toUpper), // 使用工厂函数加工，令其具备接受用户自定义的错误处理机制
    // 注册统一的错误处理函数
    registerErrorHandler(fn) {
        handleError = fn;
    },
    // 将制造的工厂函数也导出，可能在别的地方制造
    createSafeFunction,
}

```

这样，我们在开发工具函数时，只需要关注函数逻辑的书写，仅仅在最后调用工厂函数加工导出即可。

